### PR TITLE
Also download signature checksums

### LINKED ISSUE #113: Pomegranate fails to fetch signature checksums
When trying to get a signature file for checksum verification, there is an exception and the signature is not downloaded. The signature and checksums exist: https://repo.clojars.org/ch/gluet/couplet/0.2.0/

    (cemerick.pomegranate.aether/resolve-dependencies
      :repositories [["clojars" {:url "https://repo.clojars.org/"}]]
      :coordinates '[[ch.gluet/couplet "0.2.0" :extension "jar.asc"]])
    #error {
     :cause "Checksum validation failed, no checksums available"
     :via
     [{:type org.eclipse.aether.resolution.DependencyResolutionException
       :message "Could not transfer artifact ch.gluet:couplet:jar.asc:0.2.0 from/to clojars (https://repo.clojars.org/): Checksum validation failed, no checksums available"
       :at [org.eclipse.aether.internal.impl.DefaultRepositorySystem resolveDependencies "DefaultRepositorySystem.java" 342]}
      {:type org.eclipse.aether.resolution.ArtifactResolutionException
       :message "Could not transfer artifact ch.gluet:couplet:jar.asc:0.2.0 from/to clojars (https://repo.clojars.org/): Checksum validation failed, no checksums available"
       :at [org.eclipse.aether.internal.impl.DefaultArtifactResolver resolve "DefaultArtifactResolver.java" 413]}
      {:type org.eclipse.aether.transfer.ArtifactTransferException
       :message "Could not transfer artifact ch.gluet:couplet:jar.asc:0.2.0 from/to clojars (https://repo.clojars.org/): Checksum validation failed, no checksums available"
       :at [org.eclipse.aether.connector.basic.ArtifactTransportListener transferFailed "ArtifactTransportListener.java" 52]}
      {:type org.eclipse.aether.transfer.ChecksumFailureException
       :message "Checksum validation failed, no checksums available"
       :at [org.eclipse.aether.internal.impl.AbstractChecksumPolicy onNoMoreChecksums "AbstractChecksumPolicy.java" 64]}]
     :trace
     [[org.eclipse.aether.internal.impl.AbstractChecksumPolicy onNoMoreChecksums "AbstractChecksumPolicy.java" 64]
      [org.eclipse.aether.connector.basic.ChecksumValidator validate "ChecksumValidator.java" 107]
      [org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner runTask "BasicRepositoryConnector.java" 459]
      [org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner run "BasicRepositoryConnector.java" 363]
      [org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1 run "RunnableErrorForwarder.java" 75]
      [org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor execute "BasicRepositoryConnector.java" 642]
      [org.eclipse.aether.connector.basic.BasicRepositoryConnector get "BasicRepositoryConnector.java" 262]
      [org.eclipse.aether.internal.impl.DefaultArtifactResolver performDownloads "DefaultArtifactResolver.java" 489]
      [org.eclipse.aether.internal.impl.DefaultArtifactResolver resolve "DefaultArtifactResolver.java" 390]
      [org.eclipse.aether.internal.impl.DefaultArtifactResolver resolveArtifacts "DefaultArtifactResolver.java" 215]
      [org.eclipse.aether.internal.impl.DefaultRepositorySystem resolveDependencies "DefaultRepositorySystem.java" 325]
      [sun.reflect.NativeMethodAccessorImpl invoke0 "NativeMethodAccessorImpl.java" -2]
      [sun.reflect.NativeMethodAccessorImpl invoke "NativeMethodAccessorImpl.java" 62]
      [sun.reflect.DelegatingMethodAccessorImpl invoke "DelegatingMethodAccessorImpl.java" 43]
      [java.lang.reflect.Method invoke "Method.java" 498]
      [clojure.lang.Reflector invokeMatchingMethod "Reflector.java" 167]
      [clojure.lang.Reflector invokeInstanceMethod "Reflector.java" 102]
      [cemerick.pomegranate.aether$resolve_dependencies_STAR_ invokeStatic "aether.clj" 806]
      [cemerick.pomegranate.aether$resolve_dependencies_STAR_ doInvoke "aether.clj" 707]
      [clojure.lang.RestFn applyTo "RestFn.java" 137]
      [clojure.core$apply invokeStatic "core.clj" 665]
      [clojure.core$apply invoke "core.clj" 660]
      [cemerick.pomegranate.aether$resolve_dependencies invokeStatic "aether.clj" 815]
      [cemerick.pomegranate.aether$resolve_dependencies doInvoke "aether.clj" 809]
      [clojure.lang.RestFn invoke "RestFn.java" 457]
      [cemerick.pomegranate$eval2013 invokeStatic "form-init3185853473395618484.clj" 1]
      [cemerick.pomegranate$eval2013 invoke "form-init3185853473395618484.clj" 1]
      [clojure.lang.Compiler eval "Compiler.java" 7176]
      [clojure.lang.Compiler eval "Compiler.java" 7131]
      [clojure.core$eval invokeStatic "core.clj" 3214]
      [clojure.core$eval invoke "core.clj" 3210]
      [clojure.main$repl$read_eval_print__9068$fn__9071 invoke "main.clj" 414]
      [clojure.main$repl$read_eval_print__9068 invoke "main.clj" 414]
      [clojure.main$repl$fn__9077 invoke "main.clj" 435]
      [clojure.main$repl invokeStatic "main.clj" 435]
      [clojure.main$repl doInvoke "main.clj" 345]
      [clojure.lang.RestFn invoke "RestFn.java" 1523]
      [nrepl.middleware.interruptible_eval$evaluate invokeStatic "interruptible_eval.clj" 79]
      [nrepl.middleware.interruptible_eval$evaluate invoke "interruptible_eval.clj" 55]
      [nrepl.middleware.interruptible_eval$interruptible_eval$fn__1396$fn__1400 invoke "interruptible_eval.clj" 142]
      [clojure.lang.AFn run "AFn.java" 22]
      [nrepl.middleware.session$session_exec$main_loop__1497$fn__1501 invoke "session.clj" 171]
      [nrepl.middleware.session$session_exec$main_loop__1497 invoke "session.clj" 170]
      [clojure.lang.AFn run "AFn.java" 22]
      [java.lang.Thread run "Thread.java" 748]]}

This can be worked around by setting `:checksum :warn` in the repository options.

This impacts Leiningen, see technomancy/leiningen#2567. Related: #28, technomancy/leiningen#571 … has anyone ever tested this?

### PR DESCRIPTION
**Pull request by glts**
The proposed change tweaks the session configuration, such that signature checksums (files ending in `.asc.sha1`) are downloaded as well. This fixes #113, and downstream technomancy/leiningen#2567.

Details: We are currently using the (default) legacy repository layout instance that intentionally does not download signature checksums. To use the repository layout where signature checksums _are_ downloaded, the named configuration property `aether.checksums.forSignature` must be enabled.

In my view, this is a change we will have to make. In addition, we should consider going back from the `:fail` checksum policy to `:warn`, since the `:fail` policy causes checksum verification of most artefacts (all of Clojure core) to fail – that is, undo #28. This is independent of the change proposed here.

### CODE REVIEW

**Comment by glts** [comment]
Hold on. I cannot actually reproduce this in the Pomegranate tests.

I did carefully test the change in the REPL, I stepped through the Java code paths in a debugger – but I used a Leiningen REPL, so there must have been some interference. I have to investigate more.

**Comment by glts** [comment]
Clarity at last – the analysis in the original report is correct. The reason why the test already worked – indeed there are already tests for this change – is that there was a `(System/setProperty "aether.checksums.forSignature" "true")` buried in there, working around this precise problem.

To summarise:

* The default policy of `:fail` is at odds with the use of the repository layout that skips the download of signature checksums. Signature verification with Pomegranate by default always fails.
* The proposal here is to switch to the repository layout that always fetches checksums when available, that is, drop the special casing of files ending in `.asc`. This seems like an entirely sensible default for Pomegranate.

**Comment by glts** [comment]
I have pushed another commit, which may or may not be included: it honours Pomegranate clients’ existing `aether.checksums.forSignature` system property settings. That is, if anyone is passing `-Daether.checksums.forSignature=false` (??) to their JVM this will continue to work as before.

**Comment by glts** [comment]
@cemerick I’m currently trying to get `lein deps :verify` in a better shape, this pull request would help me with that … please let me know if anything is still unclear, cheers.

**Comment by cemerick** [comment]
(I feel like my ability to review this is tenuous at this point, but here goes...)

Re: `the :fail policy causes checksum verification of most artefacts (all of Clojure core) to fail`, what is the reason for this? Are Clojure jars somehow being shipped with faulty checksums?

Am I right in thinking that Leiningen is already working around this in the context of deployment? https://github.com/technomancy/leiningen/commit/2785969f1f5a45eb9a362e824aa79236a4e20761

File: src/main/clojure/cemerick/pomegranate/aether.clj [hunk 1]
```diff
@@ -138,16 +138,20 @@
...
+        session (doto session
+                  (.setLocalRepositoryManager (.newLocalRepositoryManager
+                                               repository-system
+                                               session
+                                               (LocalRepository.
+                                                (io/file (or local-repo default-local-repo)))))
+                  (.setMirrorSelector mirror-selector)
+                  (.setOffline (boolean offline?))
+                  (.setTransferListener (construct-transfer-listener transfer-listener)))]
+    (if (contains? (.getConfigProperties session) "aether.checksums.forSignature")
```
Comment (cemerick) [inline src/main/clojure/cemerick/pomegranate/aether.clj]: Am I right in thinking that someone could recover existing/previous behaviour by setting the "aether.checksums.forSignature" system property prior to this session's creation?

**Comment by glts** [comment]
And my abilities to explain this aren’t so good … let me restate the whole thing once more.

This is only an ‘ergonomic’ change, no new functionality. _With_ this change, people can use Pomegranate to download any file no matter what, JARs, POMs, signature files, it just works. _Without_ this change, people actually need to be told a little story, ‘you can resolve/download any file with Pomegranate, _except_ signature files (those ending in `.asc`): if you need to download a signature file, you need to _either_ set the JVM property `aether.checksums.forSignature=true` [to instruct Pomegranate to download the signature checksum if available], _or_ you need to pass the `:checksum :ignore` option [to ignore the checksum verification failure that naturally occurs when the signature checksum wasn’t downloaded]’.

It’s an upgrade of the user experience in Pomegranate over that of the odd Aether default. That’s it.

> Re: `the :fail policy causes checksum verification of most artefacts (all of Clojure core) to fail`, what is the reason for this? Are Clojure jars somehow being shipped with faulty checksums?

The Clojure artefacts (like many Maven central artefacts) do not have checksums of signature files uploaded (`*.asc.sha1`); in any case such dependencies need an ‘ignore’ checksum policy for verification. (This is not peculiar to Pomegranate, would be the same with Maven.) This was just a sidenote, we can postpone this discussion.

> Am I right in thinking that Leiningen is already working around this in the context of deployment?

Yes, see story above.

File: src/main/clojure/cemerick/pomegranate/aether.clj (hunk 1 above)
Comment (glts) [reply src/main/clojure/cemerick/pomegranate/aether.clj]: Absolutely

**Comment by glts** [comment]
Still interested in this (and the dependencies fix #116) …

**Comment by glts** [comment]
I’m still interested in getting this merged, see explanations above.

**Comment by glts** [comment]
@danielcompton @MalloZup @seancorfield @slipset It's been a while, I want to get this off my  plate.

Please merge (this and the other one). If you can't do it, please give me merge rights and the Maven credentials so I can make the release.

**Comment by seancorfield** [comment]
I think we should get the CI tests working again before we merge any PRs into something this critical to the ecosystem. I took a stab at that, on **master**, by changing the test matrix to OpenJDK 8 and 11 (dropping Oracle JDK 7 and Oracle JDK 9), but now tests seem to be failing while trying to retrieve artifacts from Maven Central so I'm not sure whether that's a transient failure or something else. Hopefully, someone else on "Team clj-commons" can take a look soon and get CI running again, then we can give this PR a final review.

**Comment by glts** [comment]
Looks like  a Travis problem. Since the Travis job was registered at the old location cemerick/pomegranate by user cemerick, it is possible that the project doesn't have permissions or some token at this location.

**Comment by slipset** [comment]
@seancorfield / @glts I've set up pomegranate to run on circle, which seems to work nicely.
I've only set it up for jdk8 though.

Maybe we can just remove the `.travis.yml` and just run on circle-ci?

**Comment by glts** [comment]
Sounds good to me. Probs need to update the badge in README too?

**Comment by slipset** [comment]
So everything apart from the badge (which I thought was going to be simple) seems to be working with Circle now

**Comment by slipset** [comment]
@glts are you on the clojurians slack? if so, would you mind saying hello in the #clj-commons channel?

**Comment by glts** [comment]
No, I don't use slack. I force-pushed to trigger the build, but looks like there is no CI for pull requests (tests are green of course).

**Comment by slipset** [comment]
@glts sorry about not setting up Circle correctly. If you could force-push once again, I believe this branch would be built.

**Comment by glts** [comment]
@slipset Looks good, now it worked.

**Comment by slipset** [comment]
Cool! I'll merge this then, but I'll have to wait with deploy until #120 is approved and merged

If you have the time (and expertise) to review/test #120, it would be much appreciated!

**Comment by glts** [comment]
@slipset All right. Thank you.

I don't really understand what the new pull request tries to achieve, so can't review. Again, it does not make sense to deploy the current state as it is broken. It cannot be used in Leiningen due to a dependency conflict. This is discussed and fixed in my other open pull request #116 .
